### ISSUE TITLE
Story frozen on drag issue

### ISSUE THREAD

**Issue by carekb684** [furkansarihan/story_viewer#1]
Thanks for this plugin!

I'm experiencing a issue where the story_viewer is running, I drag the widget down to cancel it, then without releasing it i drag it back up and then release. The story doesn't continue being viewed but it is frozen and it can't be dragged anymore. However the cancel button still works.

Again thanks for this plugin, hope this can be fixed. Or perhaps if i'm using it incorrectly you can let me know.

**Comment by furkansarihan** [comment]
@carekb684  Thank you for using this package!

I just fixed the wrong behaviour that you described.

But I am not going to publish it on the pub.dev, because it has some changes on StoryItemModel from last commit and I am not really sure about it.

However, you can use updated package with adding git dependency to your `pubspec.yaml` with referencing the last commit id.

```
story_viewer:
    git:
      url: https://github.com/furkansarihan/story_viewer.git
      ref: f8c3e5c13ecc2ed1c4addded8b7c26f9f1dd5634
```

I am closing this issue right now. Feel free to re-open this issue or ask something else!
